package dicom;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.pixelmed.dicom.AttributeTag;
import com.pixelmed.dicom.DicomDictionary;
import com.pixelmed.dicom.DicomDictionaryBase;
import com.pixelmed.dicom.DicomInputStream;
import com.pixelmed.dicom.Attribute;
import com.pixelmed.dicom.AttributeList;

import javax.swing.*;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;

public class App {
  private JButton button1;
  private JPanel mainPanel;
  private JTable table1;
  private JScrollPane scr;
  private JFrame frame;
  String[][] data;
  DefaultTableModel contactTableModel;

  private File file;
  private Scanner scn;
  private int length;
  private String[][] strs;
  private Set set;
  private AttributeList list;
  public static App app;

  /**
  * Method to extract the meta-data
  *
  * @return The extracted data as a 2D array.
  */
  public String[][] meta(String filePath) {
    file = new File(filePath);
    try {
      DicomInputStream dic = new DicomInputStream(file);
      System.out.println(dic);
      list = new AttributeList();
      list.setDecompressPixelData(false);
      list.read(dic);
      list.removeUnsafePrivateAttributes();
      scn = new Scanner(list.toString());
      length = list.keySet().size();
    } catch (Exception e) {
      e.printStackTrace();
    }
    itStr();
    return strs;
  }

  /**
  * Method to sturucture the extracted the META-DATA
  *
  * @return A 2D array with structured content.
  */
  private String[][] itStr() {
    strs = new String[list.size()][6];
    int i = 0;
    DicomDictionaryBase bse = new DicomDictionary();
    for (Map.Entry<AttributeTag, Attribute> entry : list.entrySet()) {
      AttributeTag key = entry.getKey();
      Attribute value = entry.getValue();
      strs[i][0] = key.toString();
      strs[i][1] = value.getVRAsString();
      strs[i][2] = Integer.toString(value.getVM());
      strs[i][3] = Long.toString(value.getVL());
      strs[i][4] = bse.getFullNameFromTag(key);
      strs[i][5] = value.getSingleStringValueOrEmptyString();
      i++;
    }
    return strs;
  }

  public App() {
    $$$setupUI$$$();
    setUpGUI();
  }

  public void setUpGUI() {
    frame = new JFrame("DICOM Project");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.getContentPane().add(mainPanel);
    button1.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Choose file with .dcm extension");
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
          System.out.println(jfc.getSelectedFile().getAbsolutePath());
          data = meta(jfc.getSelectedFile().getAbsolutePath());
          System.out.println("read!");
          String column[] = {"Tag ID", "VR", "VM", "Length", "Description", "Value"};

          contactTableModel.setDataVector(data, column);
          sizem();
          contactTableModel.fireTableDataChanged();
        }
      }
    });
    frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
    frame.pack();
    frame.setVisible(true);
  }


  public static void main(String[] args) {

    try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      App app = new App();
    } catch (Exception ex) {
      ex.printStackTrace();
    }

  }

  public void sizem() {
    TableColumn column1;
    for (int i = 0; i < 6; i++) {
      column1 = table1.getColumnModel().getColumn(i);
      if (i == 5 || i == 4) {
        column1.setPreferredWidth(500); //sport column is bigger
      } else {
        column1.setPreferredWidth(100);
      }
    }
  }

  private void createUIComponents() {
    //
    // App test = new App();
    //test.meta("D:\\kulfiKaam\\DevelopmentCode\\extractor\\src\\main\\java\\dicom\\test1.dcm");
    //String data[][] = test.itStr();
    data = new String[0][6];
    String column[] = {"Tag ID", "VR", "VM", "Length", "Description", "Value"};
    if (table1 == null) {
      table1 = new JTable() {
        public boolean isCellEditable(int nRow, int nCol) {
          return false;
        }
      };
    }
    table1.setAutoResizeMode(5);
    contactTableModel = (DefaultTableModel) table1.getModel();
    contactTableModel.setDataVector(data, column);
    scr = new JScrollPane(table1);
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    mainPanel = new JPanel();
    mainPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
    final JLabel label1 = new JLabel();
    Font label1Font = this.$$$getFont$$$("Segoe UI Semibold", Font.BOLD, 18, label1.getFont());
    if (label1Font != null) label1.setFont(label1Font);
    label1.setHorizontalAlignment(0);
    label1.setHorizontalTextPosition(0);
    label1.setText("DICOM MetaData Viewer");
    mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    button1 = new JButton();
    button1.setEnabled(true);
    button1.setHorizontalTextPosition(0);
    button1.setText("Browse");
    mainPanel.add(button1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final Spacer spacer1 = new Spacer();
    mainPanel.add(spacer1, new GridConstraints(1, 1, 4, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    scr = new JScrollPane();
    scr.setHorizontalScrollBarPolicy(32);
    mainPanel.add(scr, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    scr.setViewportView(table1);
  }

  /**
   * @noinspection ALL
   */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null) return null;
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }

}
